
const aboutMe =[{
    id:1,
    title:'Hey, I`m Junior',
    text: 'desenvolvedor React',
    emoji:'👋',
    hoveTitile:` Junior `,
    hoveTitile2:`De Oliveira`,
    hoveText:'',
    tipoEmoji:true,
    path: 'https://www.linkedin.com/in/junior-oliveira-ba22381a3/',
},{
    id:2,
    title:'Git Hub',
    text: 'Conhecer',
    emoji:'uiw:github',
    hoveTitile:` {Junior '\n' de Oliveira}`,
    hoveText:'',
    img:'',
    tipoEmoji:false,
    path: 'https://github.com/JuniorOliveiraj',
},{
    id:3,
    title:'linkedin',
    text: 'Let´s conect',
    emoji:'akar-icons:linkedin-box-fill',
    hoveTitile:` {Junior '\n' de Oliveira}`,
    hoveText:'',
    tipoEmoji:false,
    path: 'https://www.linkedin.com/in/junior-oliveira-ba22381a3/',
},{
    id:4,
    title:'Let´s Work',
    text: 'Contato',
    emoji:'vscode-icons:file-type-go-work',
    hoveTitile:`Junior de Oliveira`,
    hoveText:'',
    tipoEmoji:false,
    path: '/contato',
    img:'/static/illustrations/ConectarMobile.png',
},{
    id:5,
    title:'Insagram',
    text: 'Seguir',
    emoji:'mdi:instagram',
    hoveTitile:` {Junior '\n' de Oliveira}`,
    hoveText:'',
    tipoEmoji:false,
    path: 'https://www.instagram.com/junyor_oliveiraj/',
}];
 export default aboutMe