
const aboutMe =[{
    id:1,
    title:'Hey, I`m Junior',
    text: 'desenvolvedor React',
    emoji:'👋',
    hoveTitile:` Junior `,
    hoveTitile2:`De Oliveira`,
    hoveText:'',
    tipoEmoji:true,
    path: 'https://www.linkedin.com/in/junior-oliveira-ba22381a3/',
},{
    id:2,
    title:'Git Hub',
    text: 'SX8',
    emoji:'uiw:github',
    hoveTitile:` {Junior '\n' de Oliveira}`,
    hoveText:'',
    img:'',
    tipoEmoji:false,
    path: 'https://github.com/JuniorOliveiraj',
},{
    id:3,
    title:'Grid',
    text: 'SX4',
    emoji:'akar-icons:linkedin-box-fill',
    hoveTitile:` {Junior '\n' de Oliveira}`,
    hoveText:'',
    tipoEmoji:true,
    path: 'https://www.linkedin.com/in/junior-oliveira-ba22381a3/',
},{
    id:4,
    title:'Grid',
    text: 'SX4',
    emoji:'👋',
    hoveTitile:` {Junior '\n' de Oliveira}`,
    hoveText:'',
    tipoEmoji:true,
    path: 'https://www.linkedin.com/in/junior-oliveira-ba22381a3/',
},{
    id:5,
    title:'Grid',
    text: 'SX8',
    emoji:'👋',
    hoveTitile:` {Junior '\n' de Oliveira}`,
    hoveText:'',
    tipoEmoji:true,
    path: 'https://www.linkedin.com/in/junior-oliveira-ba22381a3/',
}];
 export default aboutMe