const imgs = [{

    id:1,
    img: `../static/mock-images/imageHome/img_${2}.jpg`,
    Text: 'Ola meu nome é Junior,  estou a 3 anos estudando e me aperfeiçoando, a fim de ser um excelente profissional e estou disposto a dar o melhor pra te ajudar em qualquer projeto.',
    title: 'Junior Oliveira',
    perfil: `../static/mock-images/imageHome/Perfil_${4}.png`,
    rota:'',
    text2:'Sobre mim',
    corFrom:'#78015f ',
    corTo:'#ee855f',
    BordaTip:2,
}, {
    id:2,
    img: `../static/mock-images/imageHome/img_${5}.jpg`,
    Text: 'Sou desenvolvedor react. estou me aperfeiçoando a cada dia. logo serei developer mobile com react native. desde já estou disposto a iniciar minha primeira experiência profissional. Como parceiro e não apenas como free Lancer. ',
    title: 'Developer React',
    perfil: `../static/mock-images/imageHome/Perfil_${6}.png`,
    rota:'',
    text2:'React',
    corFrom:'#006283 ',
    corTo:'#21c761',
    BordaTip:2,
}, {
    id:3,
    img: `../static/mock-images/imageHome/img_${4}.jpg`,
    Text: 'UI (User Interface) é a aparência visual do produto, enquanto UX (User Experience) é a experiência geral do usuário enquanto utiliza o produto. Ambos são importantes para criar produtos eficazes e agradáveis para os usuários.',
    title: 'Design de interfaces',
    perfil: `../static/mock-images/imageHome/Perfil_${5}.png`,
    rota:'',
    text2:'UI & UX',
    corFrom:'#b7c8c2',
    corTo:'#889490',
    BordaTip:1,
}]
export default imgs