const imgs = [{
    id:1,
    img: `../static/mock-images/imageHome/img_${2}.jpg`,
    Text: 'Ola meu nome é Junior,  estou a 3 anos estudando e me aperfeiçoando, a fim de ser um excelente profissional e estou disposto a dar o melhor pra te ajudar em qualquer projeto.',
    title: 'Junior Oliveira',
    perfil: `../static/mock-images/imageHome/Perfil_${2}.png`,
    rota:'',
    text2:'Sobre mim',
    corFrom:'#ffafbd ',
    corTo:'#ffc3a0',
}, {
    
    id:2,
    img: `../static/mock-images/imageHome/img_${5}.jpg`,
    Text: 'Sou desenvolvedor react. estou me aperfeiçoando a cada dia. logo serei developer mobile com react native. desde já estou disposto a iniciar minha primeira experiência profissional. Como parceiro e não apenas como free Lancer. ',
    title: 'Developer React',
    perfil: `../static/mock-images/imageHome/Perfil_${4}.png`,
    rota:'',
    text2:'React',
    corFrom:'#2193b0 ',
    corTo:'#6dd5ed',
}, {
    id:3,
    img: `../static/mock-images/imageHome/img_${4}.jpg`,
    Text: 'Estou estudando Java para Web. Com Rest, Ligação com Banco de Dados  e Tudo que tem Direito. Estou esperançoso pois estou apaixonado nessa linguagem Back-end',
    title: 'Aprendiz Java',
    perfil: `../static/mock-images/imageHome/Perfil_${5}.png`,
    rota:'',
    text2:'Java',
    corFrom:'#ee9ca7',
    corTo:'#ffdde1',
}, {
    id:4,
    img: 'https://media.giphy.com/media/siREjlLKjdSZq/giphy.gif',
    Text: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
    title: 'relational database?',
    perfil:`../static/mock-images/imageHome/Perfil_${6}.png`,
    rota:'',
    text2:'database',
    corFrom:'#42275a ',
    corTo:'#734b6d',
}, {
    id:5,
    img: 'https://media.giphy.com/media/A8NNZlVuA1LoY/giphy.gif',
    Text: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book..',
    title: 'Junior Oliveira 5',
    perfil: 'https://comoinvestir.thecap.com.br/medias/2022/01/vendas-de-nfts-do-bored-ape-yacht-club-ultrapassam-us-1-bilhao.webp',
    rota:'',
    text2:'Sobre mim',
    corFrom:'#de6262',
    corTo:'#ffb88c',
}]
export default imgs