const imgs = [{

    id:1,
    img: `../static/mock-images/imageHome/img_${2}.jpg`,
    Text: 'Ola meu nome é Junior,  estou a 3 anos estudando e me aperfeiçoando, a fim de ser um excelente profissional e estou disposto a dar o melhor pra te ajudar em qualquer projeto.',
    title: 'Junior Oliveira',
    perfil: `../static/mock-images/imageHome/Perfil_${4}.png`,
    rota:'',
    text2:'Sobre mim',
    corFrom:'#2193b0 ',
    corTo:'#6dd5ed',
    BordaTip:1,
}, {
    id:2,
    img: `../static/mock-images/imageHome/img_${5}.jpg`,
    Text: 'Sou desenvolvedor react. estou me aperfeiçoando a cada dia. logo serei developer mobile com react native. desde já estou disposto a iniciar minha primeira experiência profissional. Como parceiro e não apenas como free Lancer. ',
    title: 'Developer React',
    perfil: `../static/mock-images/imageHome/Perfil_${6}.png`,
    rota:'',
    text2:'React',
    corFrom:'#ffafbd ',
    corTo:'#ffc3a0',
    BordaTip:2,
}, {
    id:3,
    img: `../static/mock-images/imageHome/img_${4}.jpg`,
    Text: 'Estou estudando Java para Web. Com Rest, Ligação com Banco de Dados  e Tudo que tem Direito. Estou esperançoso pois estou apaixonado nessa linguagem Back-end',
    title: 'Aprendiz Java',
    perfil: `../static/mock-images/imageHome/Perfil_${5}.png`,
    rota:'',
    text2:'Java',
    corFrom:'#ee9ca7',
    corTo:'#ffdde1',
    BordaTip:1,
}]
export default imgs